/*
   Copyright 2018 The HAWQ Team.
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	internalinterfaces "github.com/hawq-cn/apiserver-example/pkg/client/informers_generated/internalversion/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// MyResources returns a MyResourceInformer.
	MyResources() MyResourceInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// MyResources returns a MyResourceInformer.
func (v *version) MyResources() MyResourceInformer {
	return &myResourceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
