/*
   Copyright 2018 The HAWQ Team.
*/

// This file was automatically generated by lister-gen

package v1alpha1

// MyResourceListerExpansion allows custom methods to be added to
// MyResourceLister.
type MyResourceListerExpansion interface{}

// MyResourceNamespaceListerExpansion allows custom methods to be added to
// MyResourceNamespaceLister.
type MyResourceNamespaceListerExpansion interface{}
